<?php

// This file is generated by Composer
require_once 'c:/php/vendor/autoload.php';

$client = new \Github\Client();
//$repositories = $client->api('user')->repositories('ornicar');


$repos = $client->api('repo')->all('start_page' => 1);

echo "first page: ".var_export($repos, TRUE);

$repos = $client->api('repo')->all('start_page' => 2);

echo "second page: ".var_export($repos, TRUE);


?>